var bankName;
console.log("====================Assignment 2===================");
console.log("====================Step 1=========================");
console.log("====================Before initialization==========");
console.log("Bank Name :"+bankName,"Datatype :"+typeof bankName);
bankName="SBI Bank";
console.log("====================After initialization===========");
console.log("Bank Name :"+bankName,"Datatype :"+typeof bankName);
var marks;
console.log("====================Step 2=========================");
console.log("====================Before initialization==========");
console.log("Marks :"+marks,"Datatype :"+typeof marks);
marks='90%';
console.log("====================After initialization===========");
console.log("Marks :"+marks,"Datatype :"+typeof marks);
var isWorking;
console.log("====================Step 3=========================");
console.log("====================Before initialization==========");
console.log("isWorking :"+isWorking,"Datatype :"+typeof isWorking);
isWorking=true;
console.log("====================After initialization===========");
console.log("isWorking :"+isWorking,"Datatype :"+typeof isWorking);
var totalCount="Hundred and Seven";
console.log("====================Step 4=========================");
console.log("==================== 4.a ==========");
console.log("TotalCount :"+totalCount,"TotalCount :"+typeof totalCount);
var totalCount=107;
console.log("==================== 4.b ==========");
console.log("TotalCount :"+totalCount,"TotalCount :"+typeof totalCount);
